### ISSUE TITLE
Hashie warnings

### ISSUE THREAD

**Issue by chandrasc** [omniauth/omniauth#872]
I receiving the following warning on rails console:
You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /home/vagrant/.rvm/gems/ruby-2.4.0@rails5.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.

Could some one help me?

**Comment by bmclean** [comment]
@chandrasc The warning is coming from hashie (as of version 3.5.0) and was introduced [here](https://github.com/intridea/hashie/pull/381).

**Comment by michaelherold** [comment]
Hi, Hashie maintainer here.

This is due to a new feature we have in Hashie that logs when you're overwriting keys via method setters. There are several places in Omniauth where this might cause a problem.

On an application level, you can just disable the Hashie logger if you aren't using Mash anywhere else in your app. You can do that with the following:

```ruby
Hashie.logger = Logger.new(nil)
```

If you're in a Rails app, do this in an initializer. Otherwise, do it during the bootstrap of your app.

I'm working on a patch to make this go away in Omniauth without user intervention.

**Comment by cmalpeli** [comment]
@michaelherold thanks.  FYI adding that initializer did not stop the warning message.

**Comment by masterkain** [comment]
I also have

```
You are setting a key that conflicts with a built-in method OmniAuth::Strategy::Options#display defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```

**Comment by michaelherold** [comment]
intridea/hashie#395 is the PR that will add functionality to let us override the warning behavior in OmniAuth. I'll get the PR for OmniAuth out as soon as I can.

**Comment by tmilewski** [comment]
Perfect! Thank you @michaelherold!

**Comment by evmorov** [comment]
You can add it to your Gemfile to suppress the warning `gem 'hashie', '~> 3.4.6'`

**Comment by nathanl** [comment]
As far as I can tell, the conflict being warned about is the fact that `:name` is a key here:

https://github.com/omniauth/omniauth/blob/v1.3.2/lib/omniauth.rb#L45

and also a method here:

https://github.com/omniauth/omniauth/blob/v1.3.2/lib/omniauth/auth_hash.rb#L34

**Comment by tmilewski** [comment]
@nathanl Yeah, while possible, this would create one heck of a breaking change.

**Comment by michaelherold** [comment]
Check out #874 for a proposed patch.

**Comment by michaelherold** [comment]
I just released Hashie v3.5.2 which has the `disable_warnings` feature for the Mash logger. Hopefully, this helps!

**Comment by tmilewski** [comment]
@michaelherold @dblock It appears we may have regressed with `disable_warnings`. If I remove the check (https://github.com/omniauth/omniauth/blob/master/lib/omniauth/key_store.rb#L11) and force it through `log_built_in_message` ... it works again.

**Comment by michaelherold** [comment]
😱 Seriously this is like playing Whack-a-Mole. Can you see if Hashie 3.5.3 fixes the issue? We have specific checks for logging in Hashie now and that should fix the problem.

The problem was the the fix in 3.5.2 didn't propagate to subclasses. 3.5.3 fixes it [here](https://github.com/intridea/hashie/pull/406).

**Comment by tmilewski** [comment]
@michaelherold That seems to do it! Thanks a lot for your help!

**Comment by JulienItard** [comment]
@michaelherold 
Hi i'm on Omniauth 1.3.1 and Hashie 3.5.5 but I still have this warning. Thanks

**Comment by michaelherold** [comment]
@JulienItard are you getting the warning due to an Omniauth method or from something else that uses Hashie?

What Omniauth providers are you using?

**Comment by JulienItard** [comment]
@michaelherold 
The exact warning is `You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /data/bsa_website/shared/bundled_gems/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/auth_hash.rb:34.` with Rails 4.2.8

**Comment by michaelherold** [comment]
You need to update to Omniauth 1.6.0+ to silence the error. 1.3.1 is too old.
